version: '3'

services:

  # NGINX (reverse proxy and load balancer)
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf  # Main NGINX config
      - ./nginx/staging.conf:/etc/nginx/conf.d/staging.conf  # Staging config
      - ./nginx/production.conf:/etc/nginx/conf.d/production.conf  # Production config
      - ./data/certbot/conf:/etc/letsencrypt  # Certbot configuration directory
      - ./data/certbot/www:/var/www/certbot  # Webroot for Certbot
    
    depends_on:
      - pacmusic-stg-1
      - pacmusic-stg-2
      - pacmusic-prod-1
      - pacmusic-prod-2
    networks:
      - pacmusic-network

  # Certbot (to handle SSL certificates)
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    networks:
      - pacmusic-network

  pacmusic-dev:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: pacmusic-dev
    environment:
      MINIO_ENDPOINT: ${MINIO_DEV_ENDPOINT}
      MINIO_ACCESS_KEY: ${MINIO_DEV_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_DEV_SECRET_KEY}
    ports:
      - 5000:5000
    networks:
      - pacmusic-network

  pacmusic-stg-1:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: pacmusic-stg-1
    environment:
      MINIO_ENDPOINT: ${MINIO_STG_ENDPOINT}
      MINIO_ACCESS_KEY: ${MINIO_STG_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_STG_SECRET_KEY}
    ports:
      - ${APP_STG_PORT_1}:5000
    networks:
      - pacmusic-network

  pacmusic-stg-2:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: pacmusic-stg-2
    environment:
      MINIO_ENDPOINT: ${MINIO_STG_ENDPOINT}
      MINIO_ACCESS_KEY: ${MINIO_STG_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_STG_SECRET_KEY}
    ports:
      - ${APP_STG_PORT_2}:5000
    networks:
      - pacmusic-network

  pacmusic-prod-1:
    image: "${APP_IMAGE}:${APP_TAG}"
    container_name: pacmusic-prod-1
    environment:
      MINIO_ENDPOINT: ${MINIO_PROD_ENDPOINT}
      MINIO_ACCESS_KEY: ${MINIO_PROD_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_PROD_SECRET_KEY}
    ports:
      - ${APP_PROD_PORT_1}:5000
    networks:
      - pacmusic-network

  pacmusic-prod-2:
    image: "${APP_IMAGE}:${APP_TAG}"
    container_name: pacmusic-prod-2
    environment:
      MINIO_ENDPOINT: ${MINIO_PROD_ENDPOINT}
      MINIO_ACCESS_KEY: ${MINIO_PROD_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_PROD_SECRET_KEY}
    ports:
      - ${APP_PROD_PORT_2}:5000
    networks:
      - pacmusic-network

networks:
  pacmusic-network:
    driver: bridge
    name: pacmusic-network

volumes:
  minio-dev-vol:
    driver: local
    name: minio-dev-vol