# This is a basic workflow to help you get started with Actions

name: Dev Testing

on:
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: dev-testing
    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Create .env file using secrets from the "dev-testing" environment
      - name: Create .env file
        run: |
          echo "MINIO_DEV_ENDPOINT=${{ secrets.MINIO_DEV_ENDPOINT }}" >> .env
          echo "MINIO_DEV_ACCESS_KEY=${{ secrets.MINIO_DEV_ACCESS_KEY }}" >> .env
          echo "MINIO_DEV_SECRET_KEY=${{ secrets.MINIO_DEV_SECRET_KEY }}" >> .env

      # Start application using Docker Compose
      - name: Start application
        run: sudo docker compose up --build --detach pacmusic-dev

      # Test application endpoint
      - name: Test application endpoint
        run: |
          sleep 10
          curl http://localhost:5000

      - name: Install testing requirements
        run: |
          pip install -r test/requirements.txt

      - name: Run tests
        run: python3 test/test.py
