# This is a basic workflow to help you get started with Actions

name: Dev Testing

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: dev-testing
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Create .env file using secrets from the "dev-testing" environment
      - name: Create .env file
        run: |
          echo "MINIO_DEV_ENDPOINT=${{ secrets.MINIO_DEV_ENDPOINT }}" >> .env
          echo "MINIO_DEV_ACCESS_KEY=${{ secrets.MINIO_DEV_ACCESS_KEY }}" >> .env
          echo "MINIO_DEV_SECRET_KEY=${{ secrets.MINIO_DEV_SECRET_KEY }}" >> .env

      # Start application using Docker Compose
      - name: Start application
        run: sudo docker compose up --build --detach pacmusic-dev

      # Test application endpoint
      - name: Test application endpoint
        run: |
          sleep 20
          curl http://localhost:5000

      # Install testing requirements
      - name: Install testing requirements
        run: pip install -r test/requirements.txt

      - name: List ChromeDriver directory
        run: ls -l /home/runner/.wdm/drivers/chromedriver/linux64/130.0.6723.69/

      # Run tests
      - name: Run tests
        run: python3 test/test.py
