name: Deploy Staging 🚀
on:
  push:
    branches: [ "main" ]
jobs:
  deploy-to-staging:
    runs-on: ubuntu-latest
    environment: staging
    
    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4
        
      # Jalankan script deployment di server staging menggunakan SSH
      - name: Run deployment script on staging server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST_STAGING }}
          username: ${{ secrets.SSH_USER_NAME_STAGING }}
          key: ${{ secrets.SSH_PRIVATE_KEY_STAGING }}
          port: ${{ secrets.SSH_HOST_STAGING_PORT }}
          debug: true
          script: |
            echo "Starting deployment..."
            
            
            echo "Deployment completed."
            
      # Test application endpoint
      - name: Test application endpoint
        run: |
          sleep 10
          curl -f ${{ secrets.STG_URL }}
